language: python
python:
  - "2.7"
  - "3.6"

# command to install dependencies
install:
  - pip install .

# commands to run tests 
script: 
  - pytest --cov=src

after_success:
  - coveralls

notifications:
  email: false